version: '3.8'

services:
  frontend:
    build:
      context: ../../material-applications/example-frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - 5000:5000
    command: ["serve", "-s", "-l", "5000", "build"]

  backend:
    build:
      context: ../../material-applications/example-backend
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    command: ["./server"]